### ISSUE TITLE
xformers error

### ISSUE THREAD

**Issue by xzh929** [fabio-sim/Depth-Anything-ONNX#1]
RuntimeError: unsupported output type: int, from operator: xformers::efficient_attention_forward_cutlass

environment
  torch:2.0.1
  cuda:11.7
  xformers:0.0.22

when use export.py to translate vits model,it occured this error.I have changed my torch and xformers version,it dosen't work.How can I solve it?

**Comment by fabio-sim** [comment]
Hi @xzh929, thank you for your interest in Depth-Anything-ONNX.

The PyTorch ONNX exporter doesn't register the xformers ops, so if you would like to export the models, please uninstall xformers first.
