### ISSUE TITLE
Training on my own customized dataset 

### ISSUE THREAD

**Issue by YacineDeghaies** [fabio-sim/Depth-Anything-ONNX#18]
Can I use this model to predict relative depth maps ?

My dataset is made of rgb images + their ground truth relative depth maps (8-bit depth maps)
If yes, do you have the training code for this model ? 

Thank you very much :)

**Comment by fabio-sim** [comment]
Hi @YacineDeghaies, thank you for your interest in Depth-Anything-ONNX.

I think you can refer to this training script: https://github.com/DepthAnything/Depth-Anything-V2/blob/main/metric_depth/train.py
