### ISSUE TITLE
Inference Time Comparison

### ISSUE THREAD

**Issue by TillBeemelmanns** [fabio-sim/Depth-Anything-ONNX#2]
Quick Question: Which image size did you use for the Inference Time Comparison ?

Bests,
Till

**Comment by fabio-sim** [comment]
Hi @TillBeemelmanns, thank you for your interest in Depth Anything ONNX.

I used RGB images from the Megadepth test dataset, resized to 518x518. Note that the model input image dimensions need to be multiples of 14.
