### ISSUE TITLE
depth_anything_v2_vits_outdoor  opset version=1

### ISSUE THREAD

**Issue by Frank198002** [fabio-sim/Depth-Anything-ONNX#20]
I find depth_anything_v2_vits.onnx's opset vesrsion=1, not 17.

import onnx

model = onnx.load('/home/XXX/projects/Model_2_RKNN/rknn/depth_anything_v2_vits.onnx')
opset_version = model.opset_import[0].version

**Comment by fabio-sim** [comment]
Hi @Frank198002, thank you for your interest in Depth-Anything-ONNX.

[depth_anything_v2_vits.onnx](https://github.com/fabio-sim/Depth-Anything-ONNX/releases/download/v2.0.0/depth_anything_v2_vits.onnx) was exported using TorchDynamo, so its versions may look different depending on which element of `model.opset_import` you access. Here are all the properties in [netron](https://netron.app/).

![image](https://github.com/user-attachments/assets/669ed1e0-4e3a-4738-961d-0c43b094e75b)
