### ISSUE TITLE
Failed to run infer.py

### ISSUE THREAD

**Issue by SilentJCR** [fabio-sim/Depth-Anything-ONNX#21]
I downloaded some .onnx models from the said link [https://github.com/fabio-sim/Depth-Anything-ONNX/releases](url), installed the prerequisites via pip install -r requirement.txt, and then tried to run infer.py, but it failed and instead showed the following error message:

**2024-08-23 13:42:25.507159776 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

2024-08-23 13:42:25.507171715 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:870 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirementsto ensure all dependencies are met.
Traceback (most recent call last):
  File "/home/Jefferson/Depth-Anything-V2/Depth-Anything-ONNX/infer.py", line 87, in <module>
    infer(**vars(args))
  File "/home/Jefferson/Depth-Anything-V2/Depth-Anything-ONNX/infer.py", line 36, in infer
    depth = session.run(None, {"image": image})[0]
  File "/root/miniconda3/envs/DepthAnything/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 216, in run
    self._validate_input(list(input_feed.keys()))
  File "/root/miniconda3/envs/DepthAnything/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 198, in _validate_input
    raise ValueError(
ValueError: Required inputs (['l_x_']) are missing from input feed (['image']).**

Not sure what I can do to deal with this.

**Comment by fabio-sim** [comment]
Hi @SilentJCR, thank you for your interest in Depth-Anything-ONNX.

You can use this script: [dynamo.py](https://github.com/fabio-sim/Depth-Anything-ONNX/blob/3128cb99056785cc843ad6deda2f53f2e2ff4272/dynamo.py) for the V2 models.

**Comment by SilentJCR** [comment]
> Hi @SilentJCR, thank you for your interest in Depth-Anything-ONNX.
> 
> You can use this script: [dynamo.py](https://github.com/fabio-sim/Depth-Anything-ONNX/blob/3128cb99056785cc843ad6deda2f53f2e2ff4272/dynamo.py) for the V2 models.

Thanks for the reply. I tried it but encountered another error.

> qt.qpa.xcb: could not connect to display 
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/root/miniconda3/envs/DepthAnythingONNX/lib/python3.11/site-packages/cv2/qt/plugins" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: xcb.

Tried some possible ways to solve it such as running the command "sudo apt install libxcb-cursor0" but it didn't seem to work.

**Comment by SilentJCR** [comment]
I guess it has something to do with me creating a conda environment inside a docker, which doesn't seem to support displaying images. Therefore, I ran the following command to have the depth map saved as an image instead of being displayed via imshow:

> python dynamo.py infer weights/depth_anything_v2_vits.onnx -i assets/sacre_coeur1.jpg -o depth.jpg

It worked as a result and I saw a depth map image saved, but the inference speed wasn't as fast as expected.

GPU: NVIDIA RTX 4090 24GB
onnx: 1.16.2
onnxruntime-gpu: 1.19.0

Models tried:  
downloaded pretrained models: depth_anything_v2_vits.onnx and  depth_anything_v2_vits_dynamic.onnx
I also used dynamo.py export to produce a vits.onnx and used it.

I imported time and used it to see how much time the inference takes by modifying the code:
```
    start_time = time.time()
    session.run_with_iobinding(binding)  # Actual inference happens here.
    end_time = time.time()
```
The time taken for inference using CUDA Execution Provider fluctuates from 650 ms to 850 ms, which just looks weird and is too slow.

I uncommented the line sess_options.optimized_model_filepath = "weights/optimized.onnx"
and ran inference again. The following warning message just showed up:

> Serializing optimized model with Graph Optimization level greater than ORT_ENABLE_EXTENDED and the NchwcTransformer enabled. The generated model may contain hardware specific optimizations, and should only be used in the same environment the model was optimized in.

The inference speed is still around 650 ms at best.
Using CPU Execution Provider resulted in faster results, around 150 ms, but still not fast enough.

What should I do to deal with his?

**Comment by fabio-sim** [comment]
Hi @SilentJCR

I think you are measuring the time for the first inference (?). When executing on ORT, the first inference involves considerable overhead. I usually do warm-up for ~5-10 iterations and then only measure the average latencies of the subsequent iterations (e.g., using a for-loop).

**Comment by SilentJCR** [comment]
> Hi @SilentJCR
> 
> I think you are measuring the time for the first inference (?). When executing on ORT, the first inference involves considerable overhead. I usually do warm-up for ~5-10 iterations and then only measure the average latencies of the subsequent iterations (e.g., using a for-loop).

You're right. I actually noticed this a few hours after making the last comment to talk about this.
I modified the code so that it took a video clip as the input and excluded the first frame for average time calculation.
Now it just looks reasonable. Thanks.
