### ISSUE TITLE
ImportError: cannot import name 'StrEnum' from 'enum' 

### ISSUE THREAD

**Issue by GerardXI** [fabio-sim/Depth-Anything-ONNX#24]
When I execute the “python dynamo.py export --encoder vits --output weights/vitb.onnx --opset 18” statement, there is an error， “ImportError: cannot import name 'StrEnum' from 'enum' ”，Could it be a problem with the environment?

**Comment by fabio-sim** [comment]
Hi @GerardXI, thank you for your interest in Depth-Anything-ONNX.

Yes, I think this is just an environment issue. `StrEnum` was added in Python 3.11. Prior versions (Python <= 3.10) used `str, Enum`.
