### ISSUE TITLE
about dynamic shape 

### ISSUE THREAD

**Issue by njfugit** [fabio-sim/Depth-Anything-ONNX#28]
This is a great project. I have some questions about the "dynamic shape" in the code. I refer to your relevant code and modify it in the original "depth-anything-v2" to export the onnx model, but I get the depth output is always fixed (1,140,140). Why is this? Hope to get your reply, thank you.

**Comment by fabio-sim** [comment]
Hi @njfugit, thank you for your interest in Depth-Anything-ONNX.

I'm not sure what modifications you made, but the 140 placeholder probably comes from this line:

https://github.com/fabio-sim/Depth-Anything-ONNX/blob/9abf814d22ac06f50fa96c9c632c30430be8a828/dynamo.py#L145

If you pass `-b 0 -h 0 -w 0` to the script, it should apply dynamic shapes with these lines:

https://github.com/fabio-sim/Depth-Anything-ONNX/blob/9abf814d22ac06f50fa96c9c632c30430be8a828/dynamo.py#L136-L142

**Comment by njfugit** [comment]
> Hi @njfugit, thank you for your interest in Depth-Anything-ONNX.
> 
> I'm not sure what modifications you made, but the 140 placeholder probably comes from this line:
> 
> https://github.com/fabio-sim/Depth-Anything-ONNX/blob/9abf814d22ac06f50fa96c9c632c30430be8a828/dynamo.py#L145
> 
> If you pass `-b 0 -h 0 -w 0` to the script, it should apply dynamic shapes with these lines:
> 
> https://github.com/fabio-sim/Depth-Anything-ONNX/blob/9abf814d22ac06f50fa96c9c632c30430be8a828/dynamo.py#L136-L142

Thanks for your reply, I understand now. The 140x140 here is just an artificially set resolution.
