### ISSUE TITLE
which exported models that predict the true metrics depth? 

### ISSUE THREAD

**Issue by nisrinaam29** [fabio-sim/Depth-Anything-ONNX#29]

**Comment by fabio-sim** [comment]
Hi @nisrinaam29, thank you for your interest in Depth-Anything-ONNX.

The exported metric models have `indoor` or `outdoor` in their names here: https://github.com/fabio-sim/Depth-Anything-ONNX/releases/tag/v2.0.0

**Comment by nisrinaam29** [comment]
depth = binding.get_outputs()[0].numpy()
then is this variable in dynamo.py is the HxW depth map in meters in numpy?
