### ISSUE TITLE
C++ inference?

### ISSUE THREAD

**Issue by antithing** [fabio-sim/Depth-Anything-ONNX#3]
Hi! Are there any plans for adding c++ inference?

Thanks!

**Comment by fabio-sim** [comment]
Hi, @antithing. Thank you for your interest in Depth Anything ONNX.

I'm not too proficient in C++, but you can have a look at [this implementation](https://github.com/spacewalk01/depth-anything-tensorrt/blob/main/depth_anything/trt_module.cpp) for the correct preprocessing steps.

**Comment by antithing** [comment]
Thank you!

**Comment by surlovely** [comment]
> Thank you!

Do you have any ideas about inferring ONNX models in C++?
