### ISSUE TITLE
Aspect ratio of input image is altered in pre-processing

### ISSUE THREAD

**Issue by YoniSmolin** [fabio-sim/Depth-Anything-ONNX#7]
In the "official" Depth Anything repo, the preprocessing transform maintains input image's aspect ratio ([link](https://github.com/LiheYoung/Depth-Anything/blob/6e780749e7772e911754a4eb00965727987f92f7/run.py#L44C13-L44C35)):

```
keep_aspect_ratio=True,
```

In this repo, the aspect ratio is not maintained ([link](https://github.com/fabio-sim/Depth-Anything-ONNX/blob/d6cc8e1e6713a2129683496b328bde675a66370d/depth_anything/util/transform.py#L256)):

```
keep_aspect_ratio=False,
```

My question - is there any particular reason to do say `keep_aspect_ratio=False` in this repo? Was that done for performance measurement reasons?

The model seems to work fine when I set `keep_aspect_ratio` to `True` (I tested this, the image fed to the model indeed maintains the original input image's aspect ratio).

**Comment by fabio-sim** [comment]
Hi @YoniSmolin, thank you for your interest. Yes, you are correct. I set it to `False` when I was measuring the latency.
